package com.yonisirote.readmyfeed.telegram.auth

class TelegramAuthException(
  message: String,
  val code: String,
  val context: Map<String, Any?> = emptyMap(),
  cause: Throwable? = null,
) : Exception(message, cause)

object TelegramAuthErrorCodes {
  const val CLIENT_NOT_STARTED = "TELEGRAM_AUTH_CLIENT_NOT_STARTED"
  const val PHONE_NUMBER_REQUIRED = "TELEGRAM_AUTH_PHONE_NUMBER_REQUIRED"
  const val PHONE_NUMBER_NOT_ALLOWED = "TELEGRAM_AUTH_PHONE_NUMBER_NOT_ALLOWED"
  const val EMAIL_ADDRESS_REQUIRED = "TELEGRAM_AUTH_EMAIL_ADDRESS_REQUIRED"
  const val EMAIL_ADDRESS_NOT_ALLOWED = "TELEGRAM_AUTH_EMAIL_ADDRESS_NOT_ALLOWED"
  const val EMAIL_CODE_REQUIRED = "TELEGRAM_AUTH_EMAIL_CODE_REQUIRED"
  const val EMAIL_CODE_NOT_ALLOWED = "TELEGRAM_AUTH_EMAIL_CODE_NOT_ALLOWED"
  const val CODE_REQUIRED = "TELEGRAM_AUTH_CODE_REQUIRED"
  const val CODE_NOT_ALLOWED = "TELEGRAM_AUTH_CODE_NOT_ALLOWED"
  const val PASSWORD_REQUIRED = "TELEGRAM_AUTH_PASSWORD_REQUIRED"
  const val PASSWORD_NOT_ALLOWED = "TELEGRAM_AUTH_PASSWORD_NOT_ALLOWED"
  const val QR_AUTH_NOT_ALLOWED = "TELEGRAM_AUTH_QR_AUTH_NOT_ALLOWED"
  const val CHAT_SELECTION_NOT_ALLOWED = "TELEGRAM_AUTH_CHAT_SELECTION_NOT_ALLOWED"
  const val LOG_OUT_NOT_ALLOWED = "TELEGRAM_AUTH_LOG_OUT_NOT_ALLOWED"
}
